stages:
  - build

default:
    tags:
      - shared-fi


build-frontend:
  stage: build
  script:
    - echo "Build fricking frontend"

build-backend:
  stage: build
  script:
    - echo "Build f-ing backend"
