version: "3.5"

services:
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "18080:8080"
    depends_on:
      - backend

volumes:
  postgres-data:
