[package]
name = "backend"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "*"

tonic = "0.4"
prost = "0.7"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }

[build-dependencies]
tonic-build = "0.4"
