[package]
name = "backend"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "*"
dotenv = "0.15.0"
grpc_layer = { path = "grpc_layer" }
tokio = { version = "1.15.0", features = [ "full" ] }
